<?php
require_once(__DIR__ . '/../php/configuracion/auth.php'); require_once(__DIR__ . '/../php/modelo/conexion.php');
$uid=(int)$_SESSION['id'];
$q=$conexion->prepare('SELECT * FROM reservas WHERE usuario_id=? ORDER BY fecha DESC, hora DESC'); $q->bind_param('i',$uid); $q->execute(); $reservas=$q->get_result();
$q=$conexion->prepare('SELECT p.*,d.estado AS estado_domicilio,d.direccion FROM pedidos p LEFT JOIN domicilios d ON d.pedido_id=p.id WHERE p.usuario_id=? ORDER BY p.id DESC'); $q->bind_param('i',$uid); $q->execute(); $pedidos=$q->get_result();
function estadoClase($estado){ return 'estado-'.str_replace(' ','-',strtolower($estado ?: 'pendiente')); }
function progreso($estado){ return $estado==='entregado'?100:($estado==='en camino'?65:25); }
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mis reservas y pedidos | La Pesquera</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"><link rel="stylesheet" href="../css/inicio.css"><link rel="stylesheet" href="../css/alerts.css"><link rel="stylesheet" href="../css/mis_reservas.css"></head><body>
<?php include(__DIR__ . '/../includes/navbar.php'); require_once(__DIR__ . '/../includes/flash.php'); flash_render(); ?>
<main class="mis-cuenta container py-5"><header class="mis-hero"><div><span class="mis-eyebrow"><i class="bi bi-person-check"></i> Mi cuenta</span><h1>Mis reservas y pedidos</h1><p>Consulta tus reservas y conoce el estado de cada domicilio en un solo lugar.</p></div><a href="menu.php" class="btn btn-warning rounded-pill px-4"><i class="bi bi-plus-lg me-1"></i> Hacer pedido</a></header>
<section class="mis-section"><div class="mis-section-title"><span><i class="bi bi-calendar2-check"></i></span><div><h2>Mis reservas</h2><p>Las reservas pendientes pueden editarse o cancelarse.</p></div></div><?php if(!$reservas->num_rows): ?><div class="mis-empty"><i class="bi bi-calendar-x"></i><p>No tienes reservas todavía.</p><a href="reservas.php" class="btn btn-outline-primary rounded-pill">Reservar una mesa</a></div><?php else: ?><div class="row g-3"><?php while($r=$reservas->fetch_assoc()): ?><div class="col-lg-6"><article class="reserva-card"><div class="reserva-date"><span><?=date('d',strtotime($r['fecha']))?></span><small><?=strtoupper(date('M',strtotime($r['fecha'])))?></small></div><div class="flex-grow-1"><div class="d-flex justify-content-between gap-2 align-items-start"><h3><?=htmlspecialchars($r['hora'])?></h3><span class="estado <?=estadoClase($r['estado'])?>"><?=htmlspecialchars(ucfirst($r['estado']))?></span></div><p><i class="bi bi-people"></i> <?=$r['personas']?> personas</p><?php if(!empty($r['observaciones'])):?><small><?=htmlspecialchars($r['observaciones'])?></small><?php endif; ?><?php if($r['estado']==='pendiente'): ?><div class="mt-3"><button class="btn btn-sm btn-outline-primary rounded-pill" data-bs-toggle="collapse" data-bs-target="#editar<?=$r['id']?>">Editar</button><form class="d-inline" method="post" action="../php/controlador/reservas/usuario_eliminar.php"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn btn-sm btn-outline-danger rounded-pill">Cancelar</button></form></div><?php endif; ?></div></article><div class="collapse edit-box" id="editar<?=$r['id']?>"><form class="row g-2" method="post" action="../php/controlador/reservas/usuario_actualizar.php"><input type="hidden" name="id" value="<?=$r['id']?>"><div class="col-md-4"><input class="form-control" type="date" name="fecha" value="<?=$r['fecha']?>" required></div><div class="col-md-4"><input class="form-control" name="hora" value="<?=htmlspecialchars($r['hora'])?>" required></div><div class="col-md-2"><input class="form-control" type="number" min="1" name="personas" value="<?=$r['personas']?>" required></div><div class="col-md-2"><button class="btn btn-warning w-100">Guardar</button></div></form></div></div><?php endwhile; ?></div><?php endif; ?></section>
<section class="mis-section"><div class="mis-section-title"><span><i class="bi bi-truck"></i></span><div><h2>Seguimiento de pedidos</h2><p>Te mostramos en qué etapa se encuentra tu domicilio.</p></div></div><?php if(!$pedidos->num_rows): ?><div class="mis-empty"><i class="bi bi-bag-x"></i><p>Aún no has realizado pedidos.</p></div><?php else: ?><div class="row g-3"><?php while($p=$pedidos->fetch_assoc()): $estado=$p['estado_domicilio']?:'pendiente'; ?><div class="col-lg-6"><article class="pedido-card"><div class="d-flex justify-content-between"><div><small>Pedido #<?=$p['id']?></small><h3>$<?=number_format((float)$p['total'],0,',','.')?></h3></div><span class="estado <?=estadoClase($estado)?>"><?=htmlspecialchars(ucfirst($estado))?></span></div><p class="pedido-address"><i class="bi bi-geo-alt"></i> <?=htmlspecialchars($p['direccion']?:'Dirección pendiente')?></p><div class="tracking"><div class="tracking-line"><span style="width:<?=progreso($estado)?>%"></span></div><div class="tracking-steps"><span class="active">Recibido</span><span class="<?=progreso($estado)>=65?'active':''?>">En camino</span><span class="<?=progreso($estado)>=100?'active':''?>">Entregado</span></div></div></article></div><?php endwhile; ?></div><?php endif; ?></section></main><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script></body></html>
