<?php
$nombre = trim($_GET['nombre'] ?? 'Plato'); $imagen = trim($_GET['imagen'] ?? ''); $precio = (int)($_GET['precio'] ?? 0);
$fichas = [
  'mojarra frita' => ['Mojarra fresca, ajo, limón y especias', 'Arroz, patacón y ensalada', 'Porción individual (450 g)', 'Pescado; puede contener trazas de gluten'],
  'cazuela de mariscos' => ['Camarón, calamar, pescado, crema de coco y verduras', 'Arroz blanco y patacón', 'Tazón de 550 ml', 'Crustáceos, moluscos, pescado y lácteos'],
  'filete de robalo' => ['Robalo, limón, ajo y hierbas', 'Arroz, ensalada y patacón', 'Filete de 250 g', 'Pescado; puede contener trazas de gluten'],
  'ensalada' => ['Lechuga, tomate, zanahoria y vinagreta', 'Sin acompañamiento', 'Porción de 180 g', 'La vinagreta puede contener mostaza'],
];
$datos = $fichas[mb_strtolower($nombre, 'UTF-8')] ?? ['Ingredientes preparados frescos según disponibilidad.', 'Consulta al personal para opciones disponibles.', 'Porción individual.', 'Informa al equipo sobre alergias antes de ordenar.'];
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=htmlspecialchars($nombre)?> | La Pesquera</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="../css/inicio.css"><link rel="stylesheet" href="../css/menu.css"></head><body class="pesquera-textured-theme"><?php include __DIR__ . '/../includes/navbar.php'; ?><main class="container py-5"><a class="btn btn-outline-secondary mb-4" href="menu.php">← Volver al menú</a><article class="card border-0 shadow-lg overflow-hidden"><div class="row g-0"><div class="col-md-6"><img class="w-100 h-100 object-fit-cover" style="min-height:360px" src="<?=htmlspecialchars($imagen)?>" alt="<?=htmlspecialchars($nombre)?>"></div><div class="col-md-6 p-4 p-lg-5"><h1><?=htmlspecialchars($nombre)?></h1><p class="h3 text-primary mb-4">$<?=number_format($precio,0,',','.')?></p><h2 class="h5">Ingredientes</h2><p><?=htmlspecialchars($datos[0])?></p><h2 class="h5">Acompañamientos</h2><p><?=htmlspecialchars($datos[1])?></p><h2 class="h5">Tamaño</h2><p><?=htmlspecialchars($datos[2])?></p><div class="alert alert-warning"><strong>Alérgenos:</strong> <?=htmlspecialchars($datos[3])?></div></div></div></article></main></body></html>
