<?php
session_start();
$correo = htmlspecialchars($_SESSION['correo_pendiente'] ?? '');
$flash = $_SESSION['flash'] ?? null;
unset($_SESSION['flash']);
?>
<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Verificar correo | La Pesquera</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"><link rel="stylesheet" href="../css/login.css"></head>
<body><main class="login-right min-vh-100 d-flex align-items-center justify-content-center p-3"><section class="login-box verification-box card shadow-lg border-0 p-4 p-md-5"><div class="verification-icon"><i class="bi bi-envelope-check"></i></div><h1 class="h3 text-center mb-3">Activa tu cuenta</h1><?php if ($flash): ?><div class="verification-notice verification-notice-<?= htmlspecialchars($flash['type'] ?? 'info') ?>" role="status"><i class="bi bi-info-circle-fill"></i><span><?= htmlspecialchars($flash['message'] ?? '') ?></span></div><?php endif; ?><p class="text-center">Te enviamos un código de 6 dígitos a <strong><?= $correo ?></strong>. Revísalo para activar tu cuenta.</p><form method="post" action="/php/controlador/verificacion.php"><input type="hidden" name="correo" value="<?= $correo ?>"><label class="form-label">Código</label><input class="form-control verification-code text-center mb-3" name="codigo" inputmode="numeric" pattern="\d{6}" maxlength="6" autocomplete="one-time-code" required autofocus><button class="btn btn-warning w-100" type="submit">Activar cuenta</button></form><form method="post" action="/php/controlador/verificacion.php" class="mt-3" id="formReenviar"><input type="hidden" name="accion" value="reenviar"><input type="hidden" name="correo" value="<?= $correo ?>"><button class="resend-code-button w-100" type="submit"><i class="bi bi-arrow-repeat"></i><span>Reenviar código</span></button></form><p class="verification-help mb-0">Si no lo ves, revisa la carpeta de spam.</p></section></main><script>document.getElementById('formReenviar')?.addEventListener('submit',function(){const b=this.querySelector('button');b.disabled=true;b.innerHTML='<span class="spinner-border spinner-border-sm"></span><span>Enviando código…</span>';});</script></body></html>
